pipeline {

 agent any

 stages {

  stage('Build') {
    steps {
      sh 'docker build -t monitoring-app .'
    }
  }

  stage('Push') {
    steps {
      sh 'docker push dockerhub/monitoring-app'
    }
  }

  stage('Deploy') {
    steps {
      sh 'ansible-playbook ansible/playbook.yml'
    }
  }

 }

}
